<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Missie.Desktop</RootNamespace>
    <AssemblyName>Missie</AssemblyName>
    <ApplicationTitle>Missie</ApplicationTitle>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\missie.ico</ApplicationIcon>
    <Version>0.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Missie.Core/Missie.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Fonts\*.ttf" />
    <Resource Include="Assets\missie.ico" />
  </ItemGroup>
</Project>
